# Generated by Django 2.2.16 on 2021-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=19, verbose_name='成交额'),
        ),
        migrations.AlterField(
            model_name='index',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=19, verbose_name='成交量'),
        ),
    ]
