# Generated by Django 2.2.16 on 2021-12-28 16:38

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20211222_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('code', models.CharField(max_length=64, verbose_name='代码')),
                ('date', models.DateField(verbose_name='时间')),
                ('open', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='收盘价')),
                ('volume', models.DecimalField(decimal_places=0, max_digits=19, verbose_name='成交量')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '指数历史数据',
                'verbose_name_plural': '指数历史数据',
            },
        ),
    ]
