# Generated by Django 2.2.16 on 2022-01-04 17:19

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_indexhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=64, verbose_name='基金简称')),
                ('code', models.CharField(max_length=64, verbose_name='基金代码')),
                ('publisher', models.CharField(max_length=64, verbose_name='发行公司')),
                ('fund_type', models.CharField(max_length=64, verbose_name='基金类型')),
                ('subscription_period', models.CharField(max_length=64, verbose_name='集中认购期')),
                ('raise_shares', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='募集份额')),
                ('date_establishment', models.DateField(verbose_name='成立日期')),
                ('established_increase', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='成立来涨幅')),
                ('fund_manager', models.CharField(max_length=64, verbose_name='基金经理')),
                ('subscription_status', models.CharField(max_length=64, verbose_name='申购状态')),
                ('discount_rate', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='优惠费率')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '新发布公墓基金',
                'verbose_name_plural': '新发布公墓基金',
            },
        ),
    ]
