# Generated by Django 2.2.16 on 2022-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_newfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfund',
            name='discount_rate',
            field=models.CharField(max_length=64, verbose_name='优惠费率'),
        ),
    ]
